services:
  postgres:
    image: postgres:17
    container_name: wechat-db
    restart: no
    ports:
      - '${DB_PORT}:5432'
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - wechat_db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: wechat-pgadmin
    restart: no
    ports:
      - '5050:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - postgres
    volumes:
      - wechat_pgadmin_data:/var/lib/pgadmin

volumes:
  wechat_db_data:
  wechat_pgadmin_data:
